# Answer
GET http://localhost:5000/answers HTTP/1.1

###
POST http://localhost:5000/answers HTTP/1.1
content-type: application/json


{
    "userID": "1320235",
    "answerText": "String",
    "listComment": [],
    "createTime": "12/5/2021",
    "whoVoteLike": [],
    "whoVoteDislike": []
}

###
GET  http://localhost:5000/answers/9846 HTTP/1.1

###
PUT  http://localhost:5000/answers/9846 HTTP/1.1
content-type: application/json

{ 
    "answerID":"9846",
    "listComment": ["8216"]
}

###
DELETE http://localhost:5000/answers/9846 HTTP/1.1
content-type: application/json

{ 
    "answerID":"9846"
}