# Forum
GET http://localhost:5000/forums HTTP/1.1

###

GET http://localhost:5000/forums?subject=sci HTTP/1.1

###

POST http://localhost:5000/forums HTTP/1.1
content-type: application/json

{
    "userID": "1",
    "title": "#1 test",
    "postText": "rgnrgnrngnrg",
    "listSubject": ["law","sci"]
}

###
GET  http://localhost:5000/forums/3 HTTP/1.1

###

GET  http://localhost:5000/forums/user/1 HTTP/1.1

###
PUT  http://localhost:5000/forums/9846146545 HTTP/1.1
content-type: application/json

{ 
    "forumID":"9846146545",
    "listTag": ["sci","c lang"],
    "listImage":["http://pngimg.com/uploads/chrome_logo/chrome_logo_PNG34.png"]
}

###
DELETE http://localhost:5000/forums/9846146545 HTTP/1.1
content-type: application/json

{ 
    "forumID":"9846146545"
}

### Tag

### 
GET http://localhost:5000/forums/tag HTTP/1.1
content-type: application/json


### 
POST http://localhost:5000/forums/tag HTTP/1.1
content-type: application/json

{
    "name": "com-sci"
}