# User
GET http://localhost:5000/users HTTP/1.1

###

###
POST http://localhost:5000/users HTTP/1.1
content-type: application/json

{
    "googleID": "5461",
    "userName": "om.apisith",
    "email":"om.apisith@gmail.com",
    "password": "knvlskfbndgbd4b4dbf",
    "firstName": "Apisith",
    "lastName": "Wongsorn",
    "imgURL": "",
    "gender": "Male",
    "birthDate": "5/1/2000",
    "bio": "Somewhere",
    "country": "TH",
    "timeRegister": "5/1/2021",
    "score": 3
}

###
GET  http://localhost:5000/users/1320235 HTTP/1.1

###
PUT  http://localhost:5000/users/1320235 HTTP/1.1
content-type: application/json

{ 
    "userID":"1320235",
    "bio": "8000",
    "imgURL": "http://pngimg.com/uploads/chrome_logo/chrome_logo_PNG34.png"
}

###
DELETE http://localhost:5000/users/4 HTTP/1.1
content-type: application/json

{ 
    "userID":"4"
}