# User
GET http://localhost:5000/users HTTP/1.1

###

GET http://localhost:5000/users/google/109585993819534771568 HTTP/1.1


###
POST http://localhost:5000/users/register HTTP/1.1
content-type: application/json

{
    "email":"apis12@gmail.com",
    "password": "12345678",
    "firstName": "Apisith",
    "lastName": "Wongsorn",
    "bio": "Somewhere",
    "role": "user"
}

###
POST http://localhost:5000/users/signin HTTP/1.1
content-type: application/json

{
    "email":"apisith.won@dome.tu.ac.th",
    "password": "APISITH**WONGSORN"
}

###
GET  http://localhost:5000/users/1 HTTP/1.1

###
PUT  http://localhost:5000/users/1 HTTP/1.1
content-type: application/json

{ 
    "userID":"1",
    "bio": "8000",
    "imgURL": "https://lh3.googleusercontent.com/a/AATXAJz5rVtFRsck9IPitC0UIrNrNEvKoTv1dYcRLryN=s96-c",
    "googleID": "109585993819534771568"
}

###
DELETE http://localhost:5000/users/4 HTTP/1.1
content-type: application/json

{ 
    "userID":"4"
}

